services:
  web:
    image: nginx:latest
    ports:
#      local port maps containers port
      - "80:80"
#  php application, custom build from Dockerfile
  app:
    build:
      dockerfile: infrastructure/php/Dockerfile