services:
  web:
    image: nginx:latest
    ports:
#      local port maps containers port
      - "80:80"
#     mapping local to container
    volumes:
      - ./infrastructure/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#  php application, custom build from Dockerfile
  app:
    build:
      dockerfile: infrastructure/php/Dockerfile
#      target multistage build - dev
      target: "${BUILD_TARGET:-app}"
    volumes:
      - ./app:/var/www/html
#     :ro => readonly
      - ./infrastructure/php/conf.d/xdebug.ini:/user/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      #      MYSQL_USER: root
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_HOST: $MYSQL_HOST
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
#      deafault value
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php
#  redis => check default port in docker ps
  cache:
    image: redis:latest

#default , docker will handle
volumes:
  mysqldata: