name: docker-php

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Install composer dependencies
#        working-directory: ./app
#        run: composer install --prefer-dist
#      - name: Run Tests
#        working-directory: ./app
#        run: composer run-phpunit
      - run: docker build --target app -t Lenny606/php-docker:1.0 -f ./infrastructure/php/Dockerfile .
      - run: docker build -t Lenny606/nginx-docker:1.0 -f ./infrastructure/nginx/Dockerfile .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push -u Lenny606/php-docker:1.0
      - run: docker push -u Lenny606/nginx-docker:1.0
